site_name: makefun
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-makefun
docs_dir: .
site_dir: ../site
nav:
    - Home: index.md
    # - API reference: api_reference.md
    - Changelog: changelog.md
#    - Advanced Usage: advanced_usage.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true